IF
  Entered([GOODCUTOFF])
  LevelPartyLT(10)
THEN
  RESPONSE #100
    DisplayString(LastTrigger,14381)  // Trap Sprung
    ForceSpell(LastTrigger,TRAP_ARROW)
END

IF
  Entered([GOODCUTOFF])
  LevelPartyGT(9)
  LevelPartyLT(15)
THEN
  RESPONSE #50
    DisplayString(LastTrigger,14381)  // Trap Sprung
    ForceSpell(LastTrigger,TRAP_ARROW)
  RESPONSE #100
    DisplayString(LastTrigger,14381)  // Trap Sprung
    ForceSpell(LastTrigger,TRAP_ARROW_BITING)
END

IF
  Entered([GOODCUTOFF])
  LevelPartyGT(14)
THEN
  RESPONSE #25
    DisplayString(LastTrigger,14381)  // Trap Sprung
    ForceSpell(LastTrigger,TRAP_ARROW)
  RESPONSE #50
    DisplayString(LastTrigger,14381)  // Trap Sprung
    ForceSpell(LastTrigger,TRAP_ARROW_BITING)
  RESPONSE #100
    DisplayString(LastTrigger,14381)  // Trap Sprung
    ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
END
