// Cutscene: Drain CHARNAME XP (high)

IF
  XPGT(Player1,9999)
  XPLT(Player1,100000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-30000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,99999)
  XPLT(Player1,200000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-60000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,199999)
  XPLT(Player1,300000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-90000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,299999)
  XPLT(Player1,400000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-120000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,399999)
  XPLT(Player1,500000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-150000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,499999)
  XPLT(Player1,600000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-180000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,599999)
  XPLT(Player1,700000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-210000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,699999)
  XPLT(Player1,800000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-240000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,799999)
  XPLT(Player1,900000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-270000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,899999)
  XPLT(Player1,1000000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-300000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,999999)
  XPLT(Player1,1100000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-330000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1099999)
  XPLT(Player1,1200000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-360000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1199999)
  XPLT(Player1,1300000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-390000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1299999)
  XPLT(Player1,1400000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-420000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1399999)
  XPLT(Player1,1500000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-450000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1499999)
  XPLT(Player1,1600000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-480000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1599999)
  XPLT(Player1,1700000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-510000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1699999)
  XPLT(Player1,1800000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-540000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1799999)
  XPLT(Player1,1900000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-570000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1899999)
  XPLT(Player1,2000000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-600000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,1999999)
  XPLT(Player1,2100000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-630000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,2099999)
  XPLT(Player1,2200000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-660000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,2199999)
  XPLT(Player1,2300000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-690000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,2299999)
  XPLT(Player1,2400000)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-720000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END

IF
  XPGT(Player1,2399999)
THEN
  RESPONSE #100
    CutSceneId(Myself)
    ForceSpellRES("a7#fx37",Player1)
    AddXPObject(Player1,-750000)
    Wait(5)
    StartCutSceneEx("a7#ct02x",TRUE)
END
